spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    # Logger에 sql문이 찍힌다.
    org.hibernate.SQL: debug
    p6spy: info